export const templateOptions = [
  {
    id: "orbit",
    name: "Orbit — Engineering velocity",
    description: "Design întunecat cu linii neon și energie de startup tech.",
    url: "https://templates.webform.site/orbit",
    preview: "/templates/orbit.html",
    thumbnail: "/templates/orbit.png",
  },
  {
    id: "yuna",
    name: "YUNA — Proactive Intelligence Platform",
    description: "Platformă predictivă cu contrast puternic și accente vibrante de portocaliu și albastru.",
    url: "https://templates.webform.site/yuna",
    preview: "/templates/yuna.html",
    thumbnail: "/templates/yuna.png",
  },
  {
    id: "aether",
    name: "AETHER — Advanced Skincare",
    description: "Design de lux pentru skincare, cu efecte de sticlă, animații la scroll și aspect editorial.",
    url: "https://templates.webform.site/aether",
    preview: "/templates/aether.html",
    thumbnail: "/templates/aether.png",
  },
  {
    id: "forward",
    name: "Forward — Next Gen Finance",
    description: "Aspect futurist pentru fintech, cu animații dinamice și secțiuni pentru developeri.",
    url: "https://templates.webform.site/forward",
    preview: "/templates/forward.html",
    thumbnail: "/templates/forward.png",
  },
  {
    id: "suki",
    name: "Sarah — Model Portfolio",
    description: "Portofoliu cinematic cu interacțiuni spectaculoase și galerie de proiecte.",
    url: "https://templates.webform.site/suki",
    preview: "/templates/suki.html",
    thumbnail: "/templates/suki.png",
  },
  {
    id: "cognitive",
    name: "Cognitive Future AI",
    description: "Consultanță AI enterprise cu tematică neurală și vizualuri impresionante.",
    url: "https://templates.webform.site/cognitive",
    preview: "/templates/cognitive.html",
    thumbnail: "/templates/cognitive.png",
  },
  {
    id: "aura",
    name: "Aura",
    description: "Layout etereal cu gradienți stratificați și încadrare elegantă.",
    url: "https://templates.webform.site/aura",
    preview: "/templates/aura.html",
    thumbnail: "/templates/aura.png",
  },
  {
    id: "archito",
    name: "Archito",
    description: "Estetică de portofoliu arhitectural cu grid-uri structurate și tipografie îndrăzneață.",
    url: "https://templates.webform.site/archito",
    preview: "/templates/archito.html",
    thumbnail: "/templates/archito.png",
  },
  {
    id: "roar",
    name: "Roar",
    description: "Pagină de brand cu impact puternic, gradienți intensi și mesaje care ies în evidență.",
    url: "https://templates.webform.site/roar",
    preview: "/templates/roar.html",
    thumbnail: "/templates/roar.png",
  },
  {
    id: "engineer-portfolio",
    name: "Engineer Portfolio",
    description: "Portofoliu personal de inginer cu secțiuni clare și proiecte în prim-plan.",
    url: "https://templates.webform.site/engineer-portfolio",
    preview: "/templates/engineer-portfolio.html",
    thumbnail: "/templates/engineer-portfolio.png",
  },
  {
    id: "flux",
    name: "Flux",
    description: "Landing SaaS plin de energie, cu animații în hero și butoane de acțiune vizibile.",
    url: "https://templates.webform.site/flux",
    preview: "/templates/flux.html",
    thumbnail: "/templates/flux.png",
  },
  {
    id: "lexora",
    name: "Lexora",
    description: "Storytelling premium de brand cu tipografie editorială și gradienți rafinați.",
    url: "https://templates.webform.site/lexora",
    preview: "/templates/lexora.html",
    thumbnail: "/templates/lexora.png",
  },
  {
    id: "gemini-motion",
    name: "Gemini Motion",
    description: "Layout cinematic cu panouri stratificate și carduri animate.",
    url: "https://templates.webform.site/gemini-motion",
    preview: "/templates/gemini-motion.html",
    thumbnail: "/templates/gemini-motion.png",
  },
  {
    id: "faster",
    name: "Faster",
    description: "Pagină de produs axată pe performanță, cu metrici clare și vizualuri de viteză.",
    url: "https://templates.webform.site/faster",
    preview: "/templates/faster.html",
    thumbnail: "/templates/faster.png",
  },
  {
    id: "form-design",
    name: "Form Design",
    description: "Experiență centrată pe formulare, cu pattern-uri UI moderne și câmpuri elegante.",
    url: "https://templates.webform.site/form-design",
    preview: "/templates/form-design.html",
    thumbnail: "/templates/form-design.png",
  },
  {
    id: "genlabs",
    name: "GenLabs",
    description: "Estetică de laborator AI cu panouri gradient și secțiuni axate pe date.",
    url: "https://templates.webform.site/genlabs",
    preview: "/templates/genlabs.html",
    thumbnail: "/templates/genlabs.png",
  },
  {
    id: "archdigest",
    name: "Archdigest",
    description: "Atmosferă de revistă de arhitectură cu imagini mari și povestire prin grid.",
    url: "https://templates.webform.site/archdigest",
    preview: "/templates/archdigest.html",
    thumbnail: "/templates/archdigest.png",
  },
  {
    id: "clarity-yield",
    name: "Clarity Yield",
    description: "Aspect de dashboard fintech cu carduri curate și elemente de încredere.",
    url: "https://templates.webform.site/clarity-yield",
    preview: "/templates/clarity-yield.html",
    thumbnail: "/templates/clarity-yield.png",
  },
  {
    id: "kreona",
    name: "Kreona",
    description: "Layout de studio creativ cu blocuri de culoare jucăușe și grid de portofoliu.",
    url: "https://templates.webform.site/kreona",
    preview: "/templates/kreona.html",
    thumbnail: "/templates/kreona.png",
  },
  {
    id: "devforge",
    name: "DevForge",
    description: "Landing pentru unelte de developer cu estetică dark și funcționalități în prim-plan.",
    url: "https://templates.webform.site/devforge",
    preview: "/templates/devforge.html",
    thumbnail: "/templates/devforge.png",
  },
] as const;
