export const templateOptions = [
  {
    id: "orbit",
    name: "Site Startup Tech",
    description: "Perfect pentru startup-uri și companii de tehnologie. Design întunecat cu linii neon și energie modernă.",
    url: "https://templates.webform.site/orbit",
    preview: "/templates/orbit.html",
    thumbnail: "/templates/orbit.png",
  },
  {
    id: "yuna",
    name: "Platformă AI & Analytics",
    description: "Ideal pentru servicii de inteligență artificială și analiză de date. Contrast puternic cu accente vibrante.",
    url: "https://templates.webform.site/yuna",
    preview: "/templates/yuna.html",
    thumbnail: "/templates/yuna.png",
  },
  {
    id: "aether",
    name: "Brand Cosmetice & Frumusețe",
    description: "Creat pentru branduri de skincare și cosmetice. Design de lux cu efecte de sticlă și animații elegante.",
    url: "https://templates.webform.site/aether",
    preview: "/templates/aether.html",
    thumbnail: "/templates/aether.png",
  },
  {
    id: "forward",
    name: "Site Fintech & Investiții",
    description: "Pentru companii financiare și platforme de investiții. Aspect futurist cu secțiuni clare pentru servicii.",
    url: "https://templates.webform.site/forward",
    preview: "/templates/forward.html",
    thumbnail: "/templates/forward.png",
  },
  {
    id: "suki",
    name: "Portofoliu Model / Artistă",
    description: "Pentru modele, actori și artiști. Layout cinematic cu galerie foto spectaculoasă.",
    url: "https://templates.webform.site/suki",
    preview: "/templates/suki.html",
    thumbnail: "/templates/suki.png",
  },
  {
    id: "cognitive",
    name: "Agenție Consultanță AI",
    description: "Pentru agenții de consultanță în inteligență artificială. Vizualuri impresionante și secțiuni pentru servicii.",
    url: "https://templates.webform.site/cognitive",
    preview: "/templates/cognitive.html",
    thumbnail: "/templates/cognitive.png",
  },
  {
    id: "aura",
    name: "Landing Page Elegant",
    description: "Template versatil pentru orice afacere. Design minimalist cu gradienți subtili și încadrare elegantă.",
    url: "https://templates.webform.site/aura",
    preview: "/templates/aura.html",
    thumbnail: "/templates/aura.png",
  },
  {
    id: "archito",
    name: "Portofoliu Arhitect",
    description: "Pentru birouri de arhitectură și designeri de interior. Grid-uri structurate pentru proiecte și tipografie îndrăzneață.",
    url: "https://templates.webform.site/archito",
    preview: "/templates/archito.html",
    thumbnail: "/templates/archito.png",
  },
  {
    id: "roar",
    name: "Brand Îndrăzneț & Agresiv",
    description: "Pentru branduri care vor să iasă în evidență. Gradienți intensi și mesaje cu impact puternic.",
    url: "https://templates.webform.site/roar",
    preview: "/templates/roar.html",
    thumbnail: "/templates/roar.png",
  },
  {
    id: "engineer-portfolio",
    name: "CV Inginer Software",
    description: "Portofoliu pentru programatori și ingineri. Secțiuni clare pentru experiență, proiecte și competențe tehnice.",
    url: "https://templates.webform.site/engineer-portfolio",
    preview: "/templates/engineer-portfolio.html",
    thumbnail: "/templates/engineer-portfolio.png",
  },
  {
    id: "flux",
    name: "Site SaaS & Aplicații",
    description: "Pentru companii software și aplicații SaaS. Plin de energie cu animații și butoane de acțiune vizibile.",
    url: "https://templates.webform.site/flux",
    preview: "/templates/flux.html",
    thumbnail: "/templates/flux.png",
  },
  {
    id: "lexora",
    name: "Brand Premium & Lux",
    description: "Pentru branduri de lux și companii premium. Tipografie editorială și gradienți rafinați.",
    url: "https://templates.webform.site/lexora",
    preview: "/templates/lexora.html",
    thumbnail: "/templates/lexora.png",
  },
  {
    id: "gemini-motion",
    name: "Studio Video & Animație",
    description: "Pentru studiouri de producție video și animație. Layout cinematic cu carduri animate și panouri stratificate.",
    url: "https://templates.webform.site/gemini-motion",
    preview: "/templates/gemini-motion.html",
    thumbnail: "/templates/gemini-motion.png",
  },
  {
    id: "faster",
    name: "Produs Tech & Performanță",
    description: "Pentru produse axate pe viteză și performanță. Metrici clare și vizualuri dinamice.",
    url: "https://templates.webform.site/faster",
    preview: "/templates/faster.html",
    thumbnail: "/templates/faster.png",
  },
  {
    id: "form-design",
    name: "Agenție UI/UX Design",
    description: "Pentru agenții de design și freelanceri UI/UX. Pattern-uri moderne și prezentare elegantă a lucrărilor.",
    url: "https://templates.webform.site/form-design",
    preview: "/templates/form-design.html",
    thumbnail: "/templates/form-design.png",
  },
  {
    id: "genlabs",
    name: "Laborator AI & Cercetare",
    description: "Pentru laboratoare de cercetare și companii de AI. Estetică științifică cu secțiuni pentru date și rezultate.",
    url: "https://templates.webform.site/genlabs",
    preview: "/templates/genlabs.html",
    thumbnail: "/templates/genlabs.png",
  },
  {
    id: "archdigest",
    name: "Revistă & Blog Arhitectură",
    description: "Pentru publicații și bloguri de arhitectură. Imagini mari și povestire vizuală prin grid editorial.",
    url: "https://templates.webform.site/archdigest",
    preview: "/templates/archdigest.html",
    thumbnail: "/templates/archdigest.png",
  },
  {
    id: "clarity-yield",
    name: "Dashboard Fintech",
    description: "Pentru platforme financiare și aplicații de investiții. Carduri curate și elemente care inspiră încredere.",
    url: "https://templates.webform.site/clarity-yield",
    preview: "/templates/clarity-yield.html",
    thumbnail: "/templates/clarity-yield.png",
  },
  {
    id: "kreona",
    name: "Studio Creativ & Design",
    description: "Pentru studiouri creative și agenții de design. Blocuri de culoare jucăușe și grid de portofoliu.",
    url: "https://templates.webform.site/kreona",
    preview: "/templates/kreona.html",
    thumbnail: "/templates/kreona.png",
  },
  {
    id: "devforge",
    name: "Unelte pentru Developeri",
    description: "Pentru produse destinate programatorilor. Estetică dark cu focus pe funcționalități și documentație.",
    url: "https://templates.webform.site/devforge",
    preview: "/templates/devforge.html",
    thumbnail: "/templates/devforge.png",
  },
] as const;
